## Travis CI configuration for the cookiecutter-perl-app project.
##
##  <https://travis-ci.org/mdklatt/cookiecutter-perl-app>
##
language: perl

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

branches:
  only:
    - master
    - dev

sudo: false

install:
  # Because this is a Perl project, a Python virtualenv is not used, and pip
  # needs to install locally.
  - pip install --requirement=requirements.txt --user

script:
  - bash test.bash
