## Perl dependencies for the {{ cookiecutter.module_name }} module.
##
## Some package managers (e.g. cpanm and carton) will automatically recognize
## this file when asked to install dependencies.
##
requires 'Pod::POM', 0;
requires 'Pod::POM::View::Restructured', 0;
